# -*- coding: utf-8 -*-
"""03_data_splitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Auq56B9J3O1AYa63PwjXdzdcZK_Aksci
"""

!pip install torch-geometric

import torch
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

graphs_save_dir = Path('/content/drive/MyDrive/ColabNotebooks/AnomalyDetection/graphs')
graphs_load_path = graphs_save_dir / 'nf_bot_iot_v2.2_graphs.pt'

try:
    graph_data = torch.load(graphs_load_path, map_location=torch.device('cpu'), weights_only=False)
    graph_sequence = graph_data['graphs']
    graph_labels = [g.y.item() for g in graph_sequence]

    node_feature_dim = graph_data['node_feature_dim']
    edge_feature_dim = len(graph_data['features'])

    print(f"Loaded {len(graph_sequence)} total graphs.")
    print(f"Node Feature Dim: {node_feature_dim}, Edge Feature Dim: {edge_feature_dim}")
except FileNotFoundError:
    print(f"Error: Graph file not found at {graphs_load_path}. Please re-run Module 02.")
    exit()

test_size = 0.15
val_size = 0.15
val_split_ratio_of_remaining = val_size / (1 - test_size)

train_val_graphs_all, test_graphs, train_val_labels_all, test_labels = train_test_split(
    graph_sequence, graph_labels,
    test_size=test_size,
    stratify=graph_labels,
    random_state=42
)

train_graphs_temp, val_graphs_temp, train_labels_temp, val_labels_temp = train_test_split(
    train_val_graphs_all, train_val_labels_all,
    test_size=val_split_ratio_of_remaining,
    stratify=train_val_labels_all,
    random_state=42
)

train_graphs = [g for i, g in enumerate(train_graphs_temp) if train_labels_temp[i] == 0]
train_labels = [0] * len(train_graphs)

val_graphs = [g for i, g in enumerate(val_graphs_temp) if val_labels_temp[i] == 0]
val_labels = [0] * len(val_graphs)

print(f"Total graphs: {len(graph_sequence)}")
print(f"Split Ratios: Train={1 - test_size - val_size:.2f}, Val={val_size:.2f}, Test={test_size:.2f}")
print("---------------------------------------------------")
print(f"  Train Set (Benign Only): {len(train_graphs)}")
print(f"  Val Set (Benign Only): {len(val_graphs)}")
print(f"  Test Set (Mixed): {len(test_graphs)}")

def print_distribution(name, labels):
    if not labels:
        print(f"  {name} Set is empty.")
        return

    counts = pd.Series(labels).value_counts().sort_index()
    print(f"{name} Set Distribution:")
    total = len(labels)
    benign_count = counts.get(0, 0)
    attack_count = counts.get(1, 0)

    print(f"  Label 0 (Benign): {benign_count} ({benign_count/total*100:.2f}%)")
    print(f"  Label 1 (Attack): {attack_count} ({attack_count/total*100:.2f}%)")
    return counts

train_label_counts = print_distribution("Training", train_labels)
val_label_counts = print_distribution("Validation", val_labels)
test_label_counts = print_distribution("Test", test_labels)

save_dir = Path('/content/drive/MyDrive/ColabNotebooks/AnomalyDetection/graphs')
save_dir.mkdir(parents=True, exist_ok=True)

torch.save(train_graphs, save_dir / 'train_graphs_benign.pt')
torch.save(val_graphs, save_dir / 'val_graphs_benign.pt')
torch.save(test_graphs, save_dir / 'test_graphs_mixed.pt')
print(f"Saved all fixed graph splits to {save_dir}")

WINDOW_SIZE = 500

torch.save({
    'node_feature_dim': node_feature_dim,
    'edge_feature_dim': edge_feature_dim,
    'window_size': graph_data.get('window_size', WINDOW_SIZE)
}, save_dir / 'graph_metadata.pt')
print(f"Saved graph metadata (features dimensions).")